# Generated by Django 2.2.1 on 2019-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_requests_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Lang_Pref',
            field=models.CharField(choices=[('EN', 'English'), ('ZH', 'Chinese'), ('HI', 'Hindi'), ('ES', 'Spanish'), ('FR', 'French'), ('AR', 'Arabic'), ('RU', 'Russian'), ('BN', 'Bengali'), ('PT', 'Portuguese'), ('ID', 'Indonesian')], default='EN', max_length=1),
        ),
    ]
