# Generated by Django 2.2.2 on 2019-06-05 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
