# Generated by Django 2.2.2 on 2019-06-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Lang_Pref',
            field=models.CharField(choices=[('EN', 'English'), ('ZH', 'Chinese'), ('HI', 'Hindi'), ('ES', 'Spanish'), ('FR', 'French'), ('AR', 'Arabic'), ('RU', 'Russian'), ('BN', 'Bengali'), ('PT', 'Portuguese'), ('ID', 'Indonesian')], default='EN', max_length=2),
        ),
    ]
